### ISSUE TITLE
Change the FONT SIZE of the page

### ISSUE THREAD

**Issue by user-test-karo** [user-test-karo/Color-Flipper#3]
As you can see the image below the font size of the webpage is kind of small. So I want the users to make it a little bit large in order to create a user friendly experience

![Screenshot 2023-12-20 124957](https://github.com/user-test-karo/Color-Flipper/assets/154407009/0767c8eb-f19d-4f13-8978-7ef5b75ebab2)

The help will be appreciated 👏

**Comment by adityasinha-code** [comment]
@user-test-karo I can fix this issue

**Comment by user-test-karo** [comment]
@adityasinha-code okay I am assigning it to you
